### PR TITLE
task_6623_init_fetch_data_collections

### PR DESCRIPTION
**Pull request by QNFC**
task_6623_init_fetch_data_collections
https://edu-redmine.framgia.vn/issues/6623

### CODE REVIEW

**Comment by QNFC** [comment]
ready

**Comment by tuanlvt-1117** [comment]
17 file . tách pull ra e

**Comment by Tuanlvt** [comment]
(commented)

**Comment by tuanlvt-1117** [comment]
commented

**Comment by QNFC** [comment]
ready

**Comment by tuanlvt-1117** [comment]
15 file tách pull ra 10 file thôi e

**Comment by tuanlvt-1117** [comment]
commented

**Pull request closed without merging**
